BEGIN;

DROP TABLE IF EXISTS search_results CASCADE;
DROP TABLE IF EXISTS chat_message CASCADE;
DROP TABLE IF EXISTS chat CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS paper_relations CASCADE;
DROP TABLE IF EXISTS paper_identifiers CASCADE;
DROP TABLE IF EXISTS identifier_types CASCADE;
DROP TABLE IF EXISTS paper_institutions CASCADE;
DROP TABLE IF EXISTS institutions CASCADE;
DROP TABLE IF EXISTS paper_authors CASCADE;
DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS papers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

COMMIT;
